management:
  health:
    mongo:
      enabled: true

# Netty Server settings
server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  data:
    mongodb:
      database: GoTogetherAppData
      uri: mongodb://localhost:27017/gotogetherappdata
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 447326512186-5q73jasje5afok6tq4rtnhrvcr54kiqv.apps.googleusercontent.com
            client-secret: r6-x0qIpqtreqJwtDLndRtpU
            redirect-uri: "{baseUrl}/login/oauth2/callback/{registrationId}"

app:
  auth:
    tokenSecret: 4512M23IFPA012312IJFD312SCVZX245TRSC
    tokenExpirationMsec: 3600000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect